# Change these first
owner: AlphaTrueCom
repo: upptime

sites:
  - name: AlphaTrueCom
    url: https://alphatrue.com

assignees:
  - toanalien
  - lugondev

status-website:
  cname: uptime.alphatrue.io
  name: AlphaTrue Uptime Status
