# Change these first
owner: AlphaTrueCom
repo: upptime

sites:
  - name: AlphaTrueCom
    url: https://alphatrue.com

assignees:
  - toanalien
  - lugondev

status-website:
  baseUrl: /upptime
  name: Your Status Website
